version: '3.4'

services:
  mmorais.api:
    image: ${DOCKER_REGISTRY-}mmoraisapi
    container_name: mmorais-api
    build:
      context: .
      dockerfile: src/MMorais.API/Dockerfile
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081      
    
    ports:      
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
       
    networks:
      - network

  postgresdb:
    image: sibedge/postgres-plv8
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UsuariosDB
    volumes:
      - './data_db/:/var/lib/postgresql/data'
    networks:
      - network
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always

networks:
  network: